version: '3.8'

services:
  ftp:
    build: .
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - UPLOADTHING_API_KEY=${UPLOADTHING_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL}
      - FTP_PASV_ADDRESS=${FTP_PASV_ADDRESS:-0.0.0.0}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped 